""" módulo com a classe para guardar as opções de idiomas """

from . import __author__

class IdiomaAplicativo:
    textos: dict[str, dict[str, str]] = {
        "pt": {
            "about": "Sobre",
            "about-title-window": "Sobre o Juntador",
            "clear": "Limpar",
            "close": "Fechar",
            "contributor": f"Um projeto de {__author__}",
            "corrupted-file": "Arquivo Corrompido\n",
            "corrupted-files": "Arquivos Corrompidos\n",
            "dark": "Escuro",
            "exit": "Sair",
            "lang_de": "Alemão",
            "lang_en": "Inglês",
            "lang_es": "Espanhol",
            "lang_it": "Italiano",
            "lang_pt": "Português",
            "language": "Idioma",
            "light": "Claro",
            "load": "Carregar",
            "merge": "Juntar",
            "no-name": "Digite um nome válido para o novo PDF",
            "options": "Opções",
            "pdf-files": "Arquivos PDF",
            "project": "Juntador de PDFs",
            "remove": "Remover",
            "select": "Selecione o Arquivo",
            "success": "Sucesso",
            "success-msg": "PDF juntado como :\n",
            "themes": "Temas",
            "title": "Bem-vindo ao Juntador de PDFs",
            "title-window": "Juntador PDFs",
            "two-or-more": "Escolha dois ou mais PDFs",
            "warning": "Aviso",
            "wrong-name": "Não escolha um arquivo PDF de origem como destino",
        },
        "en": {
            "about": "About",
            "about-title-window": "About Merger",
            "clear": "Clear",
            "close": "Close",
            "contributor": f"A project by {__author__}",
            "corrupted-file": "Corrupted File\n",
            "corrupted-files": "Corrupted Files\n",
            "dark": "Dark",
            "exit": "Exit",
            "lang_de": "German",
            "lang_en": "English",
            "lang_es": "Spanish",
            "lang_it": "Italian",
            "lang_pt": "Portuguese",
            "language": "Language",
            "light": "Light",
            "load": "Load",
            "merge": "Merge",
            "no-name": "Enter a valid name for the new PDF",
            "options": "Options",
            "pdf-files": "PDF Files",
            "project": "PDFs Merger",
            "remove": "Remove",
            "select": "Select file",
            "success": "Success",
            "success-msg": "PDF merged as :\n",
            "themes": "Themes",
            "title": "Welcome to the PDFs Merger",
            "title-window": "PDFs Merger",
            "two-or-more": "Select two or more PDFs",
            "warning": "Warning",
            "wrong-name": "Do not select a source PDF file as the destination",
        },
        "de": {
            "about": "Über",
            "about-title-window": "Über den Zusammenführer",
            "clear": "Löschen",
            "close": "Schließen",
            "contributor": f"Ein Projekt von {__author__}",
            "corrupted-file": "Beschädigte Datei\n",
            "corrupted-files": "Beschädigte Dateien\n",
            "dark": "Dunkel",
            "exit": "Beenden",
            "lang_de": "Deutsch",
            "lang_en": "Englisch",
            "lang_es": "Spanisch",
            "lang_it": "Italienisch",
            "lang_pt": "Portugiesisch",
            "language": "Sprache",
            "light": "Hell",
            "load": "Laden",
            "merge": "Zusammenführen",
            "no-name": "Geben Sie einen gültigen Namen für das neue PDF ein",
            "options": "Optionen",
            "pdf-files": "PDF-Dateien",
            "project": "PDF-Zusammenführung",
            "remove": "Entfernen",
            "select": "Datei auswählen",
            "success": "Erfolg",
            "success-msg": "PDF zusammengeführt als:\n",
            "themes": "Themen",
            "title": "Willkommen beim PDF-Zusammenführer",
            "title-window": "PDF-Zusammenführer",
            "two-or-more": "Wählen Sie zwei oder mehr PDFs aus",
            "warning": "Warnung",
            "wrong-name": "Wählen Sie keine Ausgangs-PDF-Datei als Ziel aus",
        },
        "it": {
            "about": "Informazioni",
            "about-title-window": "Informazioni sul Unificatore",
            "clear": "Cancella",
            "close": "Chiudi",
            "contributor": f"Un progetto di {__author__}",
            "corrupted-file": "File Danneggiato\n",
            "corrupted-files": "File Danneggiati\n",
            "dark": "Scuro",
            "exit": "Esci",
            "lang_de": "Tedesco",
            "lang_en": "Inglese",
            "lang_es": "Spagnolo",
            "lang_it": "Italiano",
            "lang_pt": "Portoghese",
            "language": "Lingua",
            "light": "Chiaro",
            "load": "Carica",
            "merge": "Unisci",
            "no-name": "Inserisci un nome valido per il nuovo PDF",
            "options": "Opzioni",
            "pdf-files": "File PDF",
            "project": "Unificatore PDF",
            "remove": "Rimuovi",
            "select": "Seleziona file",
            "success": "Successo",
            "success-msg": "PDF unito come:\n",
            "themes": "Temi",
            "title": "Benvenuto all\"Unificatore PDF",
            "title-window": "Unificatore PDF",
            "two-or-more": "Seleziona due o più PDF",
            "warning": "Avviso",
            "wrong-name": "Non selezionare un file PDF di origine come destinazione",
        },
        "es": {
            "about": "Acerca de",
            "about-title-window": "Acerca del Combinador",
            "clear": "Limpiar",
            "close": "Cerrar",
            "contributor": f"Un proyecto de {__author__}",
            "corrupted-file": "Archivo Corrupto\n",
            "corrupted-files": "Archivos Corruptos\n",
            "dark": "Oscuro",
            "exit": "Salir",
            "lang_de": "Alemán",
            "lang_en": "Inglés",
            "lang_es": "Español",
            "lang_it": "Italiano",
            "lang_pt": "Portugués",
            "language": "Idioma",
            "light": "Claro",
            "load": "Cargar",
            "merge": "Combinar",
            "no-name": "Ingrese un nombre válido para el nuevo PDF",
            "options": "Opciones",
            "pdf-files": "Archivos PDF",
            "project": "Combinador de PDFs",
            "remove": "Eliminar",
            "select": "Seleccionar archivo",
            "success": "Éxito",
            "success-msg": "PDF combinado como:\n",
            "themes": "Temas",
            "title": "Bienvenido al Combinador de PDFs",
            "title-window": "Combinador de PDFs",
            "two-or-more": "Seleccione dos o más PDFs",
            "warning": "Advertencia",
            "wrong-name": "No seleccione un archivo PDF de origen como destino",
        }
    }

    def __init__(self, idioma: str = "pt"):
        """ define o idioma padão """
        self.idioma: str = idioma

    def pega_texto(self, chave: str) -> str:
        return self.textos[self.idioma].get(chave, "")

    def define_texto(self, idioma: str) -> None:
        self.idioma: str = idioma
        self.atualiza_interface()

    def atualiza_interface(self) -> None:
        """ método a ser implementado pela classe filha para atualizar idioma
        da interface """
        pass
